name: SimpleORM
version: ${project.version}
main: com.mengcraft.simpleorm.ORM
author: mengcraft.com
load: STARTUP

commands:
  simpleorm:
    description: None.
    permission: simpleorm.admin

libraries:
  - 'org.avaje:ebean:2.8.1'
  - 'com.zaxxer:HikariCP:4.0.3'